ignore:
  - "src/main/java/seedu/address/ui/CommandBox.java"
  - "src/main/java/seedu/address/ui/ResultDisplay.java"
  - "src/main/java/seedu/address/ui/MainWindow.java"
  - "src/main/java/seedu/address/MainApp.java"
  - "src/main/java/seedu/address/ui/TagFolderListPanel.java"
  - "src/main/java/seedu/address/ui/TagFolderCard.java"
  - "src/main/java/seedu/address/ui/UiManager.java"

